apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

# To add common labels to manifest file
commonLabels:
  env: dev

namespace: testing-namespace

namePrefix: neron-

nameSuffix: -dev

commonAnnotations:
  branch: master

images:
  - name: nginx
    newName: haproxy
    newTag: "1.0"